#!/bin/sh

clock=$(date '+%I')

case "$clock" in
	"00") icon="ðŸ•›" ;;
	"01") icon="ðŸ•" ;;
	"02") icon="ðŸ•‘" ;;
	"03") icon="ðŸ•’" ;;
	"04") icon="ðŸ•“" ;;
	"05") icon="ðŸ•”" ;;
	"06") icon="ðŸ••" ;;
	"07") icon="ðŸ•–" ;;
	"08") icon="ðŸ•—" ;;
	"09") icon="ðŸ•˜" ;;
	"10") icon="ðŸ•™" ;;
	"11") icon="ðŸ•š" ;;
	"12") icon="ðŸ•›" ;;
esac

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -D ~/.config/calcurse -d3)" ;;
	2) setsid "$TERMINAL" -e calcurse -D ~/.config/calcurse & ;;
	3) notify-send "ðŸ“… Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac

printf '%s %s%s\n' "$(date '+%Y %b %d (%a)')" "$icon" "$(date '+%I:%M%p')"

#for europeans, use this
#printf '%s %s%s\n' "$(date '+%a %d/%m')" "$icon" "$(date '+%I:%M%p')"
